### ISSUE TITLE
Clair controller shows "404 NotFound" and keeps restarting

### ISSUE THREAD

**Issue by joaquinfll** [caruccio/openshift-clair-controller#1]
Hi,

After deploying clair-controller in Openshift the pod is not healthy and keeps restarting.

See logs attached:

[clair-controller-4-7trpb.log](https://github.com/getupcloud/openshift-clair-controller/files/2485677/clair-controller-4-7trpb.log)

Best Regards,

Joaquin

**Comment by caruccio** [comment]
Hey @nodanero sorry for the late response. Somehow this repo is not notifying on issues... 

Regarding the error, we need to modernize this code (for instance, move from TPRs to CRDs). It's not production-ready and was just a little experiment. On the other hand, If you find some time to make this change it would be really appreciated!
